### Create Account user
POST http://localhost:8000/api/v1/accounts
Content-Type: application/json

{
  "bank_name": "Bank BCA",
  "bank_account_number": "000000002",
  "balance": 1000000,
  "userId": 7
}

### Get all Account user
GET http://localhost:8000/api/v1/accounts


### Get Detail Account user by id
GET http://localhost:8000/api/v1/accounts/7

