# Create Users
POST http://localhost:8000/api/v1/authentication/register
Content-Type: application/json

{
  "name": "dewangga",
  "email": "dewangga@gmail.com",
  "password": "password123",
  "identity_type": "KTP", 
  "identity_number": "003", 
  "address": "Surabaya"
}

### Get all users
POST http://localhost:8000/api/v1/authentication/verify
Content-Type: application/json

{
  "email": "dewangga@gmail.com",
  "password": "password123"
}

### Get Specific User
GET http://localhost:8000/api/v1/authentication/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5hbWUiOiJkZXdhbmdnYSIsImVtYWlsIjoiZGV3YW5nZ2FAZ21haWwuY29tIiwiaWF0IjoxNzEzNzA1ODI5fQ.PbfvsifscthSpclalYNRwjRW73iq5eLz3uVTYbCDA2I


